/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Electricity.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Electricity.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.078, -0.286, -1.957]} scale={2.47}>
        <mesh geometry={nodes['01_-_Starting_Mesh'].geometry} material={materials.Material} scale={0.595} />
        <mesh geometry={nodes['03_-_Volume_to_Mesh_-_HAS_MATERIAL'].geometry} material={materials['Electricity.000']} scale={0.54} />
      </group>
      <mesh geometry={nodes.path1.geometry} material={materials['Material.003']} position={[0, 0.316, -2.031]} rotation={[Math.PI / 2, 0, 0]} scale={22.15} />
    </group>
  )
}

useGLTF.preload('/Electricity.glb')
